### ISSUE TITLE
Create basic documentation

### ISSUE THREAD

**Issue by ChrisDeh** [wobcom/vicky#12]
We need to add a basic README that is explaining what vicky shall do and gives a brief overview about the architecture and how to use it.

**Comment by johannwagner** [comment]
This is partly accomplished by some commits in the OIDC branch. We will extend this documentation after the merge and close this issue afterwards.

**Comment by johannwagner** [comment]
https://github.com/wobcom/vicky/blob/feature/oidc/README.md
